export const UX_COMPARE = {
  content: {
    title: 'Změny obsahu',
    stays: 'Zůstává ze sab.cz: struktura sekcí, 7 služeb, reference, čísla, SAB TARF, ProStream, jazyky, sociální sítě.',
    changes: [
      'Copy podle pravidel z copy návrhů — ne doslovný přepis sab.cz',
      'Headline z „jednička v moři" → „Víte dopředu, kolik zaplatíte"',
      'CTA s účelem — ne telefon jako jediný vstup',
      'Dva boxy → scénáře (faktura / směna teď), ne „Vsaďte na jistotu"',
      'Forward — žargon až po problému, příklad v korunách',
      '7 služeb s „pro koho" a vlastním CTA',
      'Proč SAB — konkrétní formulace, ne superlativy',
      'Proces — úvodní hovor první, smlouva až po domluvě',
      'Formulář s před-kvalifikací místo „napište nám"',
    ],
  },
  navigation: {
    title: 'Navigace',
    rows: [
      { today: 'Novinka SAB TARF', proposed: 'SAB TARF (Novinka) — zůstává' },
      { today: 'Pro klienty (mega-menu)', proposed: 'Služby (dropdown: forward, směna, platby, hlídání)' },
      { today: '—', proposed: 'Pro koho (exportéři · importéři · pravidelné platby)' },
      { today: '—', proposed: 'Jak to funguje (kotva na proces)' },
      { today: 'O nás', proposed: 'O nás' },
      { today: 'Stát se klientem + ProStream', proposed: 'Nezávazná poptávka + ProStream' },
      { today: 'CZ / EN / DE', proposed: 'Přepínač jazyka — zůstává' },
      { today: 'Pro investory v menu', proposed: 'Investoři — patička / malý odkaz, mimo hlavní cestu' },
    ],
  },
  clarity: {
    title: 'Co musí být jasné vs. co vyniká',
    clear: [
      'Headline + trust strip + widget kurzů',
      'Problém → dva vstupy (hedge / směna)',
      'Forward flow + příklad v Kč',
      '7 služeb + proces 3 kroky',
    ],
    standout: [
      'Forward — flow + příklad 50 000 EUR',
      'Primární CTA — Nezávazná konzultace / poptávka',
      'Formulář — hlavní konverze stránky',
      'Kontrast: „o 50 000 Kč víc bez forwardu"',
    ],
  },
  journey: {
    title: 'Posloupnost — cesta klienta',
    steps: [
      'Nav + SAB TARF + ProStream + jazyk',
      'Hero: přínos + kurzy',
      'Důvěra: fakta (bez opakování v hero)',
      'Problém: poznám se?',
      'Dva vstupy: faktura v cizí měně / směna teď',
      'Forward flow: 3 kroky ze sab.cz',
      'Forward příklad: 50 000 EUR',
      'Proč SAB: 6 výhod',
      'Služby: 7 položek',
      'Jak s námi obchodovat',
      'Reference',
      'Formulář',
      'Newsletter',
      'Patička — mapa + sociální sítě',
    ],
    note: 'Přínos → důvěra → rozpoznání problému → rychlý výběr → produkt (flow + čísla) → proč my → katalog → jak začít → důkaz → akce.',
  },
} as const
